[theme]
primaryColor = "#5733f6ff"
backgroundColor = "#ffffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "monospace"

borderColor = "#948fadff"

dataframeHeaderBackgroundColor = "#efeefbff"

showSidebarBorder = 1

chartCategoricalColors =  [
     "#0068c9", # blue80
     "#83c9ff", # blue40
     "#ff2b2b", # red80
     "#ffabab", # red40
     "#29b09d", # blueGreen80
     "#7defa1", # green40
     "#ff8700", # orange80
     "#ffd16a", # orange50
     "#6d3fc0", # purple80
     "#d5dae5", # gray40
 ]

chartSequentialColors =  [
     "#e4f5ff", #blue10
     "#c7ebff", #blue20
     "#a6dcff", #blue30
     "#83c9ff", #blue40
     "#60b4ff", #blue50
     "#3d9df3", #blue60
     "#1c83e1", #blue70
     "#0068c9", #blue80
     "#0054a3", #blue90
     "#004280", #blue100
]

codeTextColor = "#60c5ffff"

# Background color used for code blocks.
codeBackgroundColor = "#181818ff"

